/*
 * User API
 *
 * Api para exponer la funcionalidad de usuarios. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Net.NetworkInformation;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace MercanciaSegura.RestAPI.Models
{
    /// <summary>
    /// Estructura para agregar usuarios
    /// </summary>
    [DataContract]
    public partial class UserRequest : IEquatable<UserRequest>
    { 
        /// <summary>
        /// Gets or Sets User
        /// </summary>
        [Required]
        [StringLength(50, MinimumLength = 1)]
        [DataMember(Name = "Usuario")]
        public string usuario { get; set; }

        [Required]
        [StringLength(255, MinimumLength = 6)]
        [DataMember(Name = "password")]
        public string password { get; set; }


        [Required]
        [EmailAddress]
        [StringLength(200)]
        [DataMember(Name = "correo")]
        public string correo { get; set; }


        [DataMember(Name = "estatus")]
        public bool estatus { get; set; } = true;


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserRequest {\n");
            sb.Append("  Usuario: ").Append(usuario).Append("\n");
            sb.Append("  Password: ").Append("******").Append("\n");
            sb.Append("  Correo: ").Append(correo).Append("\n");
            sb.Append("  Estatus: ").Append(estatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }


        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UserRequest)obj);
        }

        /// <summary>
        /// Returns true if UserRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of UserRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
    (usuario == other.usuario || (usuario != null && usuario.Equals(other.usuario))) &&
    (password == other.password || (password != null && password.Equals(other.password))) &&
    (correo == other.correo || (correo != null && correo.Equals(other.correo))) &&
    estatus == other.estatus;

        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked
            {
                var hashCode = 41;
                if (usuario != null) hashCode = hashCode * 59 + usuario.GetHashCode();
                if (password != null) hashCode = hashCode * 59 + password.GetHashCode();
                if (correo != null) hashCode = hashCode * 59 + correo.GetHashCode();
                hashCode = hashCode * 59 + estatus.GetHashCode();
                return hashCode;
            }

        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(UserRequest left, UserRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UserRequest left, UserRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
