// <auto-generated />
using System;
using MercanciaSegura.DOM.ApplicationDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MercanciaSegura.DOM.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    [Migration("20260123162450_InitialCreate_v2")]
    partial class InitialCreate_v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.BeneficiarioPreferente", b =>
                {
                    b.Property<int>("BeneficiarioPreferenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Beneficiario_Preferente_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeneficiarioPreferenteId"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("Cliente_ID");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Domicilio");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<string>("RFC")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("RFC");

                    b.HasKey("BeneficiarioPreferenteId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Beneficiario_Preferente");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Cliente_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Apellido_Materno");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Apellido_Paterno");

                    b.Property<string>("Calle")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Calle");

                    b.Property<string>("Colonia")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Colonia");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Correo_Electronico");

                    b.Property<string>("Cp")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CP");

                    b.Property<decimal?>("CuotaAplicableInternacional")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Cuota_Aplicable_Internacional");

                    b.Property<decimal?>("CuotaAplicableNacional")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Cuota_Aplicable_Nacional");

                    b.Property<decimal?>("CuotaMinimaInternacional")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Cuota_Minima_Internacional");

                    b.Property<decimal?>("CuotaMinimaNacional")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Cuota_Minima_Nacional");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Estado");

                    b.Property<int?>("EstatusId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Estatus_ID");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Actualizacion");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Registro");

                    b.Property<string>("Municipio")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Municipio");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Nacionalidad");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Nombre_Completo");

                    b.Property<string>("Nombres")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Nombres");

                    b.Property<string>("NumeroExt")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Numero_Ext");

                    b.Property<string>("NumeroInt")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Numero_Int");

                    b.Property<int?>("OrigenClienteId")
                        .HasColumnType("int")
                        .HasColumnName("Origen_Cliente_ID");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Pais");

                    b.Property<string>("Poblacion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Poblacion");

                    b.Property<int?>("RegimenFiscalId")
                        .HasColumnType("int")
                        .HasColumnName("Regimen_Fiscal_ID");

                    b.Property<string>("Rfc")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("RFC");

                    b.Property<int?>("RfcGenericoId")
                        .HasColumnType("int")
                        .HasColumnName("RfcGenerico_ID");

                    b.Property<string>("Telefono")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("Telefono");

                    b.Property<int?>("TipoCuentaId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Cuenta_ID");

                    b.Property<int?>("TipoPersonaId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Persona_ID");

                    b.Property<int?>("TipoSectorId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Sector_ID");

                    b.Property<int?>("TipoSeguroId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Seguro_ID");

                    b.HasKey("ClienteId");

                    b.HasIndex("EstatusId");

                    b.HasIndex("OrigenClienteId");

                    b.HasIndex("RegimenFiscalId");

                    b.HasIndex("RfcGenericoId");

                    b.HasIndex("TipoCuentaId");

                    b.HasIndex("TipoPersonaId");

                    b.HasIndex("TipoSectorId");

                    b.HasIndex("TipoSeguroId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.OrigenCliente", b =>
                {
                    b.Property<int>("OrigenClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Origen_Cliente_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrigenClienteId"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("OrigenClienteId");

                    b.ToTable("Origen_Cliente");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.RegimenFiscal", b =>
                {
                    b.Property<int>("RegimenFiscalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Regimen_Fiscal_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegimenFiscalId"));

                    b.Property<bool>("AplicaFisica")
                        .HasColumnType("bit")
                        .HasColumnName("Aplica_Fisica");

                    b.Property<bool>("AplicaMoral")
                        .HasColumnType("bit")
                        .HasColumnName("Aplica_Moral");

                    b.Property<int?>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("Codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descripcion");

                    b.HasKey("RegimenFiscalId");

                    b.ToTable("Regimen_Fiscal");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.RfcGenerico", b =>
                {
                    b.Property<int>("RfcGenericoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RfcGenerico_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RfcGenericoId"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("RfcGenericoId");

                    b.ToTable("RfcGenerico");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.TipoCuenta", b =>
                {
                    b.Property<int>("TipoCuentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Cuenta_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoCuentaId"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("TipoCuentaId");

                    b.ToTable("Tipo_Cuenta");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.TipoEstatus", b =>
                {
                    b.Property<int>("EstatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Estatus_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstatusID"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("EstatusID");

                    b.ToTable("Tipo_Estatus");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.TipoPersona", b =>
                {
                    b.Property<int>("TipoPersonaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Persona_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoPersonaID"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("TipoPersonaID");

                    b.ToTable("Tipo_Persona");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.TipoSector", b =>
                {
                    b.Property<int>("TipoSectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Sector_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoSectorId"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("TipoSectorId");

                    b.ToTable("Tipo_Sector");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.TipoSeguro", b =>
                {
                    b.Property<int>("TipoSeguroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Seguro_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoSeguroId"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("TipoSeguroId");

                    b.ToTable("Tipo_Seguro");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.TipoVendedor", b =>
                {
                    b.Property<int>("TipoVendedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Vendedor_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoVendedorId"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Tipo");

                    b.HasKey("TipoVendedorId");

                    b.ToTable("Tipo_Vendedor");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Usuario_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Correo");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit")
                        .HasColumnName("Estatus");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Registro");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Vendedor", b =>
                {
                    b.Property<int>("VendedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Vendedor_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendedorId"));

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Apellido_Materno");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Apellido_Paterno");

                    b.Property<string>("Clave")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Clave");

                    b.Property<string>("Colonia")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Colonia");

                    b.Property<decimal?>("Comision")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Comision");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Correo_Electronico");

                    b.Property<string>("Cp")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CP");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Domicilio");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Estado");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit")
                        .HasColumnName("Estatus");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Actualizacion");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Registro");

                    b.Property<string>("Genero")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Genero");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Nombre_Completo");

                    b.Property<string>("Nombres")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Nombres");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Observaciones");

                    b.Property<string>("Rfc")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("RFC");

                    b.Property<string>("Telefono")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("Telefono");

                    b.Property<string>("TipoPersona")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Tipo_Persona");

                    b.Property<int?>("TipoVendedorId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Vendedor_ID");

                    b.HasKey("VendedorId");

                    b.HasIndex("TipoVendedorId");

                    b.ToTable("Vendedor");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.BeneficiarioPreferente", b =>
                {
                    b.HasOne("MercanciaSegura.DOM.Modelos.Cliente", "Cliente")
                        .WithMany("BeneficiariosPreferentes")
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente", b =>
                {
                    b.HasOne("MercanciaSegura.DOM.Modelos.TipoEstatus", "TipoEstatus")
                        .WithMany()
                        .HasForeignKey("EstatusId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.OrigenCliente", "OrigenCliente")
                        .WithMany()
                        .HasForeignKey("OrigenClienteId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.RegimenFiscal", "RegimenFiscal")
                        .WithMany()
                        .HasForeignKey("RegimenFiscalId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.RfcGenerico", "RfcGenerico")
                        .WithMany()
                        .HasForeignKey("RfcGenericoId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.TipoCuenta", "TipoCuenta")
                        .WithMany()
                        .HasForeignKey("TipoCuentaId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.TipoPersona", "TipoPersona")
                        .WithMany()
                        .HasForeignKey("TipoPersonaId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.TipoSector", "TipoSector")
                        .WithMany()
                        .HasForeignKey("TipoSectorId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.TipoSeguro", "TipoSeguro")
                        .WithMany()
                        .HasForeignKey("TipoSeguroId");

                    b.Navigation("OrigenCliente");

                    b.Navigation("RegimenFiscal");

                    b.Navigation("RfcGenerico");

                    b.Navigation("TipoCuenta");

                    b.Navigation("TipoEstatus");

                    b.Navigation("TipoPersona");

                    b.Navigation("TipoSector");

                    b.Navigation("TipoSeguro");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Vendedor", b =>
                {
                    b.HasOne("MercanciaSegura.DOM.Modelos.TipoVendedor", "TipoVendedor")
                        .WithMany()
                        .HasForeignKey("TipoVendedorId");

                    b.Navigation("TipoVendedor");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente", b =>
                {
                    b.Navigation("BeneficiariosPreferentes");
                });
#pragma warning restore 612, 618
        }
    }
}
