// <auto-generated />
using System;
using MercanciaSegura.DOM.ApplicationDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MercanciaSegura.DOM.Migrations
{
    [DbContext(typeof(ServiceDbContext))]
    [Migration("20260219175127_v1.1_Poliza")]
    partial class v11_Poliza
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.BeneficiarioPreferente", b =>
                {
                    b.Property<int>("BeneficiarioPreferenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Beneficiario_Preferente_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeneficiarioPreferenteId"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("Cliente_ID");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Domicilio");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<string>("RFC")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("RFC");

                    b.HasKey("BeneficiarioPreferenteId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Beneficiario_Preferente");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Cliente_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Apellido_Materno");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Apellido_Paterno");

                    b.Property<string>("Calle")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Calle");

                    b.Property<string>("Clave")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Clave");

                    b.Property<string>("Colonia")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Colonia");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Correo_Electronico");

                    b.Property<string>("Cp")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CP");

                    b.Property<decimal?>("CuotaAplicableInternacional")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Cuota_Aplicable_Internacional");

                    b.Property<decimal?>("CuotaAplicableNacional")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Cuota_Aplicable_Nacional");

                    b.Property<decimal?>("CuotaMinimaInternacional")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Cuota_Minima_Internacional");

                    b.Property<decimal?>("CuotaMinimaNacional")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Cuota_Minima_Nacional");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Estado");

                    b.Property<int?>("EstatusId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Estatus_ID");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Actualizacion");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Baja");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Registro");

                    b.Property<string>("Genero")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Genero");

                    b.Property<string>("Municipio")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Municipio");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Nacionalidad");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Nombre_Completo");

                    b.Property<string>("Nombres")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Nombres");

                    b.Property<string>("NumeroExt")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Numero_Ext");

                    b.Property<string>("NumeroInt")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Numero_Int");

                    b.Property<int?>("OrigenClienteId")
                        .HasColumnType("int")
                        .HasColumnName("Origen_Cliente_ID");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Pais");

                    b.Property<string>("Poblacion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Poblacion");

                    b.Property<int?>("RegimenFiscalId")
                        .HasColumnType("int")
                        .HasColumnName("Regimen_Fiscal_ID");

                    b.Property<string>("Rfc")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("RFC");

                    b.Property<int?>("RfcGenericoId")
                        .HasColumnType("int")
                        .HasColumnName("RfcGenerico_ID");

                    b.Property<string>("Telefono")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("Telefono");

                    b.Property<int?>("TipoCuentaId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Cuenta_ID");

                    b.Property<int?>("TipoPersonaId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Persona_ID");

                    b.Property<int?>("TipoSectorId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Sector_ID");

                    b.Property<int?>("TipoSeguroId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Seguro_ID");

                    b.HasKey("ClienteId");

                    b.HasIndex("EstatusId");

                    b.HasIndex("OrigenClienteId");

                    b.HasIndex("RegimenFiscalId");

                    b.HasIndex("RfcGenericoId");

                    b.HasIndex("TipoCuentaId");

                    b.HasIndex("TipoPersonaId");

                    b.HasIndex("TipoSectorId");

                    b.HasIndex("TipoSeguroId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.ClienteCredito", b =>
                {
                    b.Property<int>("ClienteCreditoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Cliente_Creditos_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteCreditoId"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("Cliente_ID");

                    b.Property<int?>("DiasDeCredito")
                        .HasColumnType("int")
                        .HasColumnName("Dias_De_Credito");

                    b.Property<string>("DiasDePago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Dias_De_Pago");

                    b.Property<string>("DiasDeRevision")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Dias_De_Revision");

                    b.Property<decimal?>("LimiteDeCredito")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Limite_De_Credito");

                    b.Property<string>("MetodoDePago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Metodo_De_Pago");

                    b.Property<string>("NumeroCuenta")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Numero_Cuenta");

                    b.Property<decimal?>("Saldo")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Saldo");

                    b.HasKey("ClienteCreditoId");

                    b.HasIndex("ClienteId")
                        .IsUnique()
                        .HasFilter("[Cliente_ID] IS NOT NULL");

                    b.ToTable("Cliente_Creditos");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.Correos", b =>
                {
                    b.Property<int>("CorreoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Correo_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CorreoId"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("Cliente_ID");

                    b.Property<string>("Correo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Correo");

                    b.Property<int?>("TipoCorreoId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Correo_ID");

                    b.HasKey("CorreoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TipoCorreoId");

                    b.ToTable("Correos");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.Cuota", b =>
                {
                    b.Property<int>("CuotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Cuota_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuotaId"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("Cliente_ID");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Monto");

                    b.Property<int?>("TipoCuotaId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Cuota_ID");

                    b.Property<int?>("TipoTarifaId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Tarifa_ID");

                    b.HasKey("CuotaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TipoCuotaId");

                    b.HasIndex("TipoTarifaId");

                    b.ToTable("Cuota");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.OrigenCliente", b =>
                {
                    b.Property<int>("OrigenClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Origen_Cliente_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrigenClienteId"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("OrigenClienteId");

                    b.ToTable("Origen_Cliente");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.RegimenFiscal", b =>
                {
                    b.Property<int>("RegimenFiscalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Regimen_Fiscal_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegimenFiscalId"));

                    b.Property<bool>("AplicaFisica")
                        .HasColumnType("bit")
                        .HasColumnName("Aplica_Fisica");

                    b.Property<bool>("AplicaMoral")
                        .HasColumnType("bit")
                        .HasColumnName("Aplica_Moral");

                    b.Property<int?>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("Codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descripcion");

                    b.HasKey("RegimenFiscalId");

                    b.ToTable("Regimen_Fiscal");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.RfcGenerico", b =>
                {
                    b.Property<int>("RfcGenericoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RfcGenerico_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RfcGenericoId"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("RfcGenericoId");

                    b.ToTable("RfcGenerico");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.TipoCorreo", b =>
                {
                    b.Property<int>("TipoCorreoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Correo_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoCorreoId"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("TipoCorreoId");

                    b.ToTable("Tipo_Correo");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.TipoCuenta", b =>
                {
                    b.Property<int>("TipoCuentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Cuenta_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoCuentaId"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("TipoCuentaId");

                    b.ToTable("Tipo_Cuenta");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.TipoCuota", b =>
                {
                    b.Property<int>("TipoCuotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Cuota_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoCuotaId"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("TipoCuotaId");

                    b.ToTable("Tipo_Cuota");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.TipoEstatus", b =>
                {
                    b.Property<int>("EstatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Estatus_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstatusId"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("EstatusId");

                    b.ToTable("Tipo_Estatus");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.TipoSector", b =>
                {
                    b.Property<int>("TipoSectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Sector_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoSectorId"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("TipoSectorId");

                    b.ToTable("Tipo_Sector");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.TipoSeguro", b =>
                {
                    b.Property<int>("TipoSeguroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Seguro_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoSeguroId"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("TipoSeguroId");

                    b.ToTable("Tipo_Seguro");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.TipoTarifa", b =>
                {
                    b.Property<int>("TipoTarifaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Tarifa_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoTarifaId"));

                    b.Property<string>("Tarifa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tarifa");

                    b.HasKey("TipoTarifaId");

                    b.ToTable("Tipo_Tarifa");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.ClienteVendedor", b =>
                {
                    b.Property<int>("ClienteVendedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Cliente_Vendedor_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteVendedorId"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("Cliente_ID");

                    b.Property<decimal?>("Comision")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Comision");

                    b.Property<int?>("VendedorId")
                        .HasColumnType("int")
                        .HasColumnName("Vendedor_ID");

                    b.HasKey("ClienteVendedorId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Cliente_Vendedor");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.Aseguradora", b =>
                {
                    b.Property<int>("AseguradoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Aseguradora_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AseguradoraId"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("AseguradoraId");

                    b.ToTable("Aseguradora");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.Bien", b =>
                {
                    b.Property<int>("BienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Bien_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BienId"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Nombre");

                    b.Property<int>("PolizaId")
                        .HasColumnType("int")
                        .HasColumnName("Poliza_ID");

                    b.Property<int>("TipoBienId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Bien");

                    b.HasKey("BienId");

                    b.HasIndex("PolizaId");

                    b.HasIndex("TipoBienId");

                    b.ToTable("Bien");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.Cobertura", b =>
                {
                    b.Property<int>("CoberturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Cobertura_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoberturaId"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Nombre");

                    b.Property<int>("PolizaContenedorId")
                        .HasColumnType("int")
                        .HasColumnName("Poliza_Contenedor_ID");

                    b.HasKey("CoberturaId");

                    b.HasIndex("PolizaContenedorId");

                    b.ToTable("Cobertura");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.Contratante", b =>
                {
                    b.Property<int>("ContratanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Contratante_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContratanteId"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("ContratanteId");

                    b.ToTable("Contratante");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.EstatusPoliza", b =>
                {
                    b.Property<int>("EstatusPolizaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Estatus_Poliza_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstatusPolizaId"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("EstatusPolizaId");

                    b.ToTable("Estatus_Poliza");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.FormaPago", b =>
                {
                    b.Property<int>("FormaPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FormaPago_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormaPagoId"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("FormaPagoId");

                    b.ToTable("FormaPago");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.Moneda", b =>
                {
                    b.Property<int>("MonedaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Moneda_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonedaId"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<decimal?>("TipoCambio")
                        .HasMaxLength(100)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Tipo_Cambio");

                    b.Property<decimal?>("TipoCambioVentanilla")
                        .HasMaxLength(100)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Tipo_Cambio_Ventanilla");

                    b.HasKey("MonedaId");

                    b.ToTable("Moneda");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.Poliza", b =>
                {
                    b.Property<int>("PolizaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Poliza_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolizaId"));

                    b.Property<int?>("AseguradoraId")
                        .HasColumnType("int")
                        .HasColumnName("Aseguradora_ID");

                    b.Property<string>("ClaveAgente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Clave_Agente");

                    b.Property<int?>("ContratanteId")
                        .HasColumnType("int")
                        .HasColumnName("Contratante_ID");

                    b.Property<decimal?>("DerechoPoliza")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Derecho_Poliza");

                    b.Property<int?>("EstatusPolizaId")
                        .HasColumnType("int")
                        .HasColumnName("Estatus_Poliza_ID");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Actualizacion");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Baja");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Registro");

                    b.Property<string>("FolioPoliza")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Folio_Poliza");

                    b.Property<int?>("FormaPagoId")
                        .HasColumnType("int")
                        .HasColumnName("Forma_Pago_ID");

                    b.Property<decimal?>("IVA")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("IVA");

                    b.Property<int?>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("Moneda_ID");

                    b.Property<string>("NumeroPoliza")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Numero_Poliza");

                    b.Property<decimal?>("Otros")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Otros");

                    b.Property<string>("OtrosPoliza")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Otros_Poliza");

                    b.Property<decimal?>("PrimaNeta")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Prima_Neta");

                    b.Property<decimal?>("PrimaTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Prima_Total");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("Producto_ID");

                    b.Property<int?>("SubRamoId")
                        .HasColumnType("int")
                        .HasColumnName("SubRamo_ID");

                    b.Property<string>("TipoPoliza")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Tipo_Poliza");

                    b.Property<DateTime?>("VigenciaDel")
                        .HasColumnType("datetime2")
                        .HasColumnName("Vigencia_Del");

                    b.Property<DateTime?>("VigenciaHasta")
                        .HasColumnType("datetime2")
                        .HasColumnName("Vigencia_Hasta");

                    b.HasKey("PolizaId");

                    b.HasIndex("AseguradoraId");

                    b.HasIndex("ContratanteId");

                    b.HasIndex("EstatusPolizaId");

                    b.HasIndex("FormaPagoId");

                    b.HasIndex("MonedaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("SubRamoId");

                    b.ToTable("Poliza");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.PolizaContenedor", b =>
                {
                    b.Property<int>("PolizaContenedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Poliza_Contenedor_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolizaContenedorId"));

                    b.Property<decimal?>("CuotaAplicable")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Cuota_Aplicable");

                    b.Property<decimal?>("DanioMaterial")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Danio_Material");

                    b.Property<decimal?>("Ferrocarril")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Ferrocarril");

                    b.Property<decimal?>("MedioTransporte")
                        .HasMaxLength(250)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Medio_Transporte");

                    b.Property<string>("NombreInternoPoliza")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Nombre_Interno_Poliza");

                    b.Property<decimal?>("PerdidaParcial")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Perdida_Parcial");

                    b.Property<decimal?>("PerdidaTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Perdida_Total");

                    b.Property<int>("PolizaId")
                        .HasColumnType("int")
                        .HasColumnName("Poliza_ID");

                    b.Property<decimal?>("PorContenedor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Por_Contenedor");

                    b.Property<decimal?>("Robo")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Robo");

                    b.Property<decimal?>("Terrestre")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Terrestre");

                    b.Property<string>("TrayectosAsegurados")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Trayectos_Asegurados");

                    b.HasKey("PolizaContenedorId");

                    b.HasIndex("PolizaId")
                        .IsUnique();

                    b.ToTable("Poliza_Contenedor");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.PolizaMercancia", b =>
                {
                    b.Property<int>("PolizaMercanciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Poliza_Mercancia_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolizaMercanciaId"));

                    b.Property<string>("BienesUsados")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Bienes_Usados");

                    b.Property<decimal?>("CobreAluminioAcero")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Cobre_Aluminio_Acero");

                    b.Property<string>("Compras")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Compras");

                    b.Property<decimal?>("CuotaGeneralPoliza")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Cuota_General_Poliza");

                    b.Property<string>("Deducibles")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)")
                        .HasColumnName("Deducibles");

                    b.Property<string>("EmbarqueFiliales")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Embarque_Filiales");

                    b.Property<decimal?>("EqContratistas")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("EQ_Contratistas");

                    b.Property<string>("IndemnizacionOtros")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Indemnizacion_Otros");

                    b.Property<string>("Maquila")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Maquila");

                    b.Property<decimal?>("Maritimo")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Maritimo");

                    b.Property<decimal?>("Medicamentos")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Medicamentos");

                    b.Property<decimal?>("MedicamentosControlados")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Medicamentos_Controlados");

                    b.Property<string>("NombreInternoPoliza")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Nombre_Interno_Poliza");

                    b.Property<decimal?>("PaqueteriaMensajeria")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Paqueteria_Mensajeria");

                    b.Property<int>("PolizaId")
                        .HasColumnType("int")
                        .HasColumnName("Poliza_ID");

                    b.Property<decimal?>("TerrestreAereo")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Terrestre_Aereo");

                    b.Property<string>("Ventas")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Ventas");

                    b.HasKey("PolizaMercanciaId");

                    b.HasIndex("PolizaId")
                        .IsUnique();

                    b.ToTable("Poliza_Mercancia");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Producto_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<string>("Pantalla")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Pantalla");

                    b.HasKey("ProductoId");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.RiesgoCubierto", b =>
                {
                    b.Property<int>("RiesgoCubiertoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Riesgo_Cubierto_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RiesgoCubiertoId"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<int>("PolizaMercanciaId")
                        .HasColumnType("int")
                        .HasColumnName("Poliza_Mercancia_ID");

                    b.Property<int>("TipoRiesgoId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Riesgo_ID");

                    b.HasKey("RiesgoCubiertoId");

                    b.HasIndex("PolizaMercanciaId");

                    b.ToTable("Riesgo_Cubierto");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.SubRamo", b =>
                {
                    b.Property<int>("SubRamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubRamo_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubRamoId"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("SubRamoId");

                    b.ToTable("SubRamo");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.TipoBien", b =>
                {
                    b.Property<int>("TipoBienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Bien_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoBienId"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("TipoBienId");

                    b.ToTable("Tipo_Bien");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.TipoRiesgo", b =>
                {
                    b.Property<int>("TipoRiesgoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Riesgo_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoRiesgoId"));

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nombre");

                    b.HasKey("TipoRiesgoId");

                    b.ToTable("Tipo_Riesgo");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.TipoPersona", b =>
                {
                    b.Property<int>("TipoPersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Persona_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoPersonaId"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tipo");

                    b.HasKey("TipoPersonaId");

                    b.ToTable("Tipo_Persona");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Usuario_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Correo");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit")
                        .HasColumnName("Estatus");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Registro");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Password");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Vendedor.TipoVendedor", b =>
                {
                    b.Property<int>("TipoVendedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Vendedor_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoVendedorId"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Tipo");

                    b.HasKey("TipoVendedorId");

                    b.ToTable("Tipo_Vendedor");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Vendedor.Vendedor", b =>
                {
                    b.Property<int>("VendedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Vendedor_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendedorId"));

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Apellido_Materno");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Apellido_Paterno");

                    b.Property<string>("Clave")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Clave");

                    b.Property<string>("Colonia")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Colonia");

                    b.Property<decimal?>("Comision")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Comision");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Correo_Electronico");

                    b.Property<string>("Cp")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CP");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Domicilio");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Estado");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit")
                        .HasColumnName("Estatus");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Actualizacion");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Baja");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha_Registro");

                    b.Property<string>("Genero")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Genero");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Nombre_Completo");

                    b.Property<string>("Nombres")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Nombres");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Observaciones");

                    b.Property<string>("Rfc")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("RFC");

                    b.Property<string>("Telefono")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("Telefono");

                    b.Property<int?>("TipoPersonaId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Persona_ID");

                    b.Property<int?>("TipoVendedorId")
                        .HasColumnType("int")
                        .HasColumnName("Tipo_Vendedor_ID");

                    b.HasKey("VendedorId");

                    b.HasIndex("TipoPersonaId");

                    b.HasIndex("TipoVendedorId");

                    b.ToTable("Vendedor");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.BeneficiarioPreferente", b =>
                {
                    b.HasOne("MercanciaSegura.DOM.Modelos.Cliente.Cliente", "Cliente")
                        .WithMany("BeneficiarioPreferente")
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.Cliente", b =>
                {
                    b.HasOne("MercanciaSegura.DOM.Modelos.Cliente.TipoEstatus", "TipoEstatus")
                        .WithMany()
                        .HasForeignKey("EstatusId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.Cliente.OrigenCliente", "OrigenCliente")
                        .WithMany()
                        .HasForeignKey("OrigenClienteId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.Cliente.RegimenFiscal", "RegimenFiscal")
                        .WithMany()
                        .HasForeignKey("RegimenFiscalId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.Cliente.RfcGenerico", "RfcGenerico")
                        .WithMany()
                        .HasForeignKey("RfcGenericoId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.Cliente.TipoCuenta", "TipoCuenta")
                        .WithMany()
                        .HasForeignKey("TipoCuentaId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.TipoPersona", "TipoPersona")
                        .WithMany()
                        .HasForeignKey("TipoPersonaId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.Cliente.TipoSector", "TipoSector")
                        .WithMany()
                        .HasForeignKey("TipoSectorId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.Cliente.TipoSeguro", "TipoSeguro")
                        .WithMany()
                        .HasForeignKey("TipoSeguroId");

                    b.Navigation("OrigenCliente");

                    b.Navigation("RegimenFiscal");

                    b.Navigation("RfcGenerico");

                    b.Navigation("TipoCuenta");

                    b.Navigation("TipoEstatus");

                    b.Navigation("TipoPersona");

                    b.Navigation("TipoSector");

                    b.Navigation("TipoSeguro");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.ClienteCredito", b =>
                {
                    b.HasOne("MercanciaSegura.DOM.Modelos.Cliente.Cliente", "Cliente")
                        .WithOne("ClienteCredito")
                        .HasForeignKey("MercanciaSegura.DOM.Modelos.Cliente.ClienteCredito", "ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.Correos", b =>
                {
                    b.HasOne("MercanciaSegura.DOM.Modelos.Cliente.Cliente", "Cliente")
                        .WithMany("Correos")
                        .HasForeignKey("ClienteId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.Cliente.TipoCorreo", "TipoCorreo")
                        .WithMany()
                        .HasForeignKey("TipoCorreoId");

                    b.Navigation("Cliente");

                    b.Navigation("TipoCorreo");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.Cuota", b =>
                {
                    b.HasOne("MercanciaSegura.DOM.Modelos.Cliente.Cliente", "Cliente")
                        .WithMany("Cuota")
                        .HasForeignKey("ClienteId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.Cliente.TipoCuota", "TipoCuota")
                        .WithMany()
                        .HasForeignKey("TipoCuotaId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.Cliente.TipoTarifa", "TipoTarifa")
                        .WithMany()
                        .HasForeignKey("TipoTarifaId");

                    b.Navigation("Cliente");

                    b.Navigation("TipoCuota");

                    b.Navigation("TipoTarifa");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.ClienteVendedor", b =>
                {
                    b.HasOne("MercanciaSegura.DOM.Modelos.Cliente.Cliente", "Cliente")
                        .WithMany("ClienteVendedor")
                        .HasForeignKey("ClienteId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.Vendedor.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId");

                    b.Navigation("Cliente");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.Bien", b =>
                {
                    b.HasOne("MercanciaSegura.DOM.Modelos.Poliza.Poliza", "Poliza")
                        .WithMany("Bien")
                        .HasForeignKey("PolizaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MercanciaSegura.DOM.Modelos.Poliza.TipoBien", "TipoBien")
                        .WithMany()
                        .HasForeignKey("TipoBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poliza");

                    b.Navigation("TipoBien");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.Cobertura", b =>
                {
                    b.HasOne("MercanciaSegura.DOM.Modelos.Poliza.PolizaContenedor", "PolizaContenedor")
                        .WithMany("Cobertura")
                        .HasForeignKey("PolizaContenedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolizaContenedor");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.Poliza", b =>
                {
                    b.HasOne("MercanciaSegura.DOM.Modelos.Poliza.Aseguradora", "Aseguradora")
                        .WithMany()
                        .HasForeignKey("AseguradoraId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.Poliza.Contratante", "Contratante")
                        .WithMany()
                        .HasForeignKey("ContratanteId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.Poliza.EstatusPoliza", "EstatusPoliza")
                        .WithMany()
                        .HasForeignKey("EstatusPolizaId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.Poliza.FormaPago", "FormaPago")
                        .WithMany()
                        .HasForeignKey("FormaPagoId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.Poliza.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.Poliza.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.Poliza.SubRamo", "SubRamo")
                        .WithMany()
                        .HasForeignKey("SubRamoId");

                    b.Navigation("Aseguradora");

                    b.Navigation("Contratante");

                    b.Navigation("EstatusPoliza");

                    b.Navigation("FormaPago");

                    b.Navigation("Moneda");

                    b.Navigation("Producto");

                    b.Navigation("SubRamo");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.PolizaContenedor", b =>
                {
                    b.HasOne("MercanciaSegura.DOM.Modelos.Poliza.Poliza", "Poliza")
                        .WithOne("PolizaContenedor")
                        .HasForeignKey("MercanciaSegura.DOM.Modelos.Poliza.PolizaContenedor", "PolizaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poliza");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.PolizaMercancia", b =>
                {
                    b.HasOne("MercanciaSegura.DOM.Modelos.Poliza.Poliza", "Poliza")
                        .WithOne("PolizaMercancia")
                        .HasForeignKey("MercanciaSegura.DOM.Modelos.Poliza.PolizaMercancia", "PolizaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poliza");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.RiesgoCubierto", b =>
                {
                    b.HasOne("MercanciaSegura.DOM.Modelos.Poliza.PolizaMercancia", null)
                        .WithMany("RiesgoCubierto")
                        .HasForeignKey("PolizaMercanciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Vendedor.Vendedor", b =>
                {
                    b.HasOne("MercanciaSegura.DOM.Modelos.TipoPersona", "TipoPersona")
                        .WithMany()
                        .HasForeignKey("TipoPersonaId");

                    b.HasOne("MercanciaSegura.DOM.Modelos.Vendedor.TipoVendedor", "TipoVendedor")
                        .WithMany()
                        .HasForeignKey("TipoVendedorId");

                    b.Navigation("TipoPersona");

                    b.Navigation("TipoVendedor");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Cliente.Cliente", b =>
                {
                    b.Navigation("BeneficiarioPreferente");

                    b.Navigation("ClienteCredito");

                    b.Navigation("ClienteVendedor");

                    b.Navigation("Correos");

                    b.Navigation("Cuota");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.Poliza", b =>
                {
                    b.Navigation("Bien");

                    b.Navigation("PolizaContenedor");

                    b.Navigation("PolizaMercancia");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.PolizaContenedor", b =>
                {
                    b.Navigation("Cobertura");
                });

            modelBuilder.Entity("MercanciaSegura.DOM.Modelos.Poliza.PolizaMercancia", b =>
                {
                    b.Navigation("RiesgoCubierto");
                });
#pragma warning restore 612, 618
        }
    }
}
