/*
 * User API
 *
 * Api para exponer la funcionalidad de usuarios. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Template.RestAPI.Models
{
    /// <summary>
    /// Standard error
    /// </summary>
    [DataContract]
    public partial class InlineResponse400Errors : IEquatable<InlineResponse400Errors>
    { 
        /// <summary>
        /// Error key for internationalization purposes
        /// </summary>
        /// <value>Error key for internationalization purposes</value>
        [Required]

        [DataMember(Name="errorCode")]
        public string ErrorCode { get; set; }

        /// <summary>
        /// Original URI
        /// </summary>
        /// <value>Original URI</value>
        [Required]

        [DataMember(Name="type")]
        public string Type { get; private set; }

        /// <summary>
        /// Error title, clear and concise
        /// </summary>
        /// <value>Error title, clear and concise</value>
        [Required]

        [DataMember(Name="title")]
        public string Title { get; private set; }

        /// <summary>
        /// HTTP status for the specific error
        /// </summary>
        /// <value>HTTP status for the specific error</value>
        [Required]

        [DataMember(Name="status")]
        public int? Status { get; private set; }

        /// <summary>
        /// Full detail of the error
        /// </summary>
        /// <value>Full detail of the error</value>
        [Required]

        [MinLength(15)]
        [DataMember(Name="detail")]
        public string Detail { get; private set; }

        /// <summary>
        /// Specific instance where the error occurs without the base URI
        /// </summary>
        /// <value>Specific instance where the error occurs without the base URI</value>
        [Required]

        [MinLength(1)]
        [DataMember(Name="instance")]
        public string Instance { get; private set; }

        /// <summary>
        /// Gets or Sets ExtraAttributes
        /// </summary>

        [DataMember(Name="extraAttributes")]
        public InlineResponse400ExtraAttributes ExtraAttributes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse400Errors {\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Detail: ").Append(Detail).Append("\n");
            sb.Append("  Instance: ").Append(Instance).Append("\n");
            sb.Append("  ExtraAttributes: ").Append(ExtraAttributes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineResponse400Errors)obj);
        }

        /// <summary>
        /// Returns true if InlineResponse400Errors instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponse400Errors to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse400Errors other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ErrorCode == other.ErrorCode ||
                    ErrorCode != null &&
                    ErrorCode.Equals(other.ErrorCode)
                ) && 
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                ) && 
                (
                    Title == other.Title ||
                    Title != null &&
                    Title.Equals(other.Title)
                ) && 
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                ) && 
                (
                    Detail == other.Detail ||
                    Detail != null &&
                    Detail.Equals(other.Detail)
                ) && 
                (
                    Instance == other.Instance ||
                    Instance != null &&
                    Instance.Equals(other.Instance)
                ) && 
                (
                    ExtraAttributes == other.ExtraAttributes ||
                    ExtraAttributes != null &&
                    ExtraAttributes.Equals(other.ExtraAttributes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ErrorCode != null)
                    hashCode = hashCode * 59 + ErrorCode.GetHashCode();
                    if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                    if (Title != null)
                    hashCode = hashCode * 59 + Title.GetHashCode();
                    if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (Detail != null)
                    hashCode = hashCode * 59 + Detail.GetHashCode();
                    if (Instance != null)
                    hashCode = hashCode * 59 + Instance.GetHashCode();
                    if (ExtraAttributes != null)
                    hashCode = hashCode * 59 + ExtraAttributes.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineResponse400Errors left, InlineResponse400Errors right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineResponse400Errors left, InlineResponse400Errors right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
