/*
 * User API
 *
 * Api para exponer la funcionalidad de usuarios. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Template.RestAPI.Models
{
    /// <summary>
    /// Estructura para consultar usuarios
    /// </summary>
    [DataContract]
    public partial class UserResult : IEquatable<UserResult>
    { 
        /// <summary>
        /// Gets or Sets User
        /// </summary>
        [Required]

        [StringLength(100, MinimumLength=1)]
        [DataMember(Name="user")]
        public string User { get; set; }

        /// <summary>
        /// Guid of the key-value configuration
        /// </summary>
        /// <value>Guid of the key-value configuration</value>
        [Required]

        [DataMember(Name="guid")]
        public Guid? Guid { get; set; }

        /// <summary>
        /// Creation timestamp
        /// </summary>
        /// <value>Creation timestamp</value>
        [Required]

        [DataMember(Name="creationTimestamp")]
        public DateTime? CreationTimestamp { get; set; }

        /// <summary>
        /// Modification timestamp
        /// </summary>
        /// <value>Modification timestamp</value>
        [Required]

        [DataMember(Name="modificationTimestamp")]
        public DateTime? ModificationTimestamp { get; set; }

        /// <summary>
        /// Guid of the creation user
        /// </summary>
        /// <value>Guid of the creation user</value>
        [Required]

        [DataMember(Name="creationUser")]
        public Guid? CreationUser { get; set; }

        /// <summary>
        /// Guid of the modification user
        /// </summary>
        /// <value>Guid of the modification user</value>
        [Required]

        [DataMember(Name="modificationUser")]
        public Guid? ModificationUser { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserResult {\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  Guid: ").Append(Guid).Append("\n");
            sb.Append("  CreationTimestamp: ").Append(CreationTimestamp).Append("\n");
            sb.Append("  ModificationTimestamp: ").Append(ModificationTimestamp).Append("\n");
            sb.Append("  CreationUser: ").Append(CreationUser).Append("\n");
            sb.Append("  ModificationUser: ").Append(ModificationUser).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UserResult)obj);
        }

        /// <summary>
        /// Returns true if UserResult instances are equal
        /// </summary>
        /// <param name="other">Instance of UserResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserResult other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    User == other.User ||
                    User != null &&
                    User.Equals(other.User)
                ) && 
                (
                    Guid == other.Guid ||
                    Guid != null &&
                    Guid.Equals(other.Guid)
                ) && 
                (
                    CreationTimestamp == other.CreationTimestamp ||
                    CreationTimestamp != null &&
                    CreationTimestamp.Equals(other.CreationTimestamp)
                ) && 
                (
                    ModificationTimestamp == other.ModificationTimestamp ||
                    ModificationTimestamp != null &&
                    ModificationTimestamp.Equals(other.ModificationTimestamp)
                ) && 
                (
                    CreationUser == other.CreationUser ||
                    CreationUser != null &&
                    CreationUser.Equals(other.CreationUser)
                ) && 
                (
                    ModificationUser == other.ModificationUser ||
                    ModificationUser != null &&
                    ModificationUser.Equals(other.ModificationUser)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (User != null)
                    hashCode = hashCode * 59 + User.GetHashCode();
                    if (Guid != null)
                    hashCode = hashCode * 59 + Guid.GetHashCode();
                    if (CreationTimestamp != null)
                    hashCode = hashCode * 59 + CreationTimestamp.GetHashCode();
                    if (ModificationTimestamp != null)
                    hashCode = hashCode * 59 + ModificationTimestamp.GetHashCode();
                    if (CreationUser != null)
                    hashCode = hashCode * 59 + CreationUser.GetHashCode();
                    if (ModificationUser != null)
                    hashCode = hashCode * 59 + ModificationUser.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UserResult left, UserResult right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UserResult left, UserResult right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
