/*
 * Authentication RBAC Service API
 *
 * This API will expose the functionality authentication and RBAC service
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Microsoft.AspNetCore.Mvc;
using Template.RestAPI.Attributes;
using Template.RestAPI.Controllers.Base;

namespace Template.RestAPI.Controllers
{
    /// <summary>
    ///
    /// </summary>
    [ApiController]
    public abstract class HealthApiControllerBase : ServiceBaseController
    {
        /// <summary>
        /// Ping echo for testing the service is up
        /// </summary>
        /// <remarks>Health check for the service</remarks>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/{version::apiVersion}/health")]
        //[Authorize]
        [ValidateModelState]
        public abstract IActionResult GetHealth();

        /// <summary>
        /// Readiness check by executing base functionality
        /// </summary>
        /// <remarks>Readiness check for the service</remarks>
        /// <response code="200">OK</response>
        /// <response code="400">Example response</response>
        [HttpGet]
        [Route("/{version::apiVersion}/ready")]
        //[Authorize]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 400, type: typeof(object))]
        public abstract IActionResult GetReady();
    }
}
