/*
 * Authentication RBAC Service API
 *
 * This API will expose the functionality authentication and RBAC service
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using Microsoft.AspNetCore.Mvc;

namespace Template.RestAPI.Controllers.Implementation
{
    /// <summary>
    ///
    /// </summary>
    [ApiController]
    public class HealthApiController : HealthApiControllerBase
    {
        public override IActionResult GetHealth()
        {
            // Return 200
            return this.Ok();
        }

        public override IActionResult GetReady()
        {
            // Return 200
            return this.Ok();
        }
    }
}
